---

version: "2"

plugins:
  grep:
    enabled: true

    config:
      patterns:
        no-trailing-whitespace:
          pattern: \s*$
          annotation: "Don't leave trailing whitespace"
          severity: minor
          categories: Style
          path_patterns:
            - .rubocop.yml
            - .rubocop_todo.yml
            - .travis.yml

        no-tabs:
          pattern: "	"
          annotation: "Don't use hard tabs"
          severity: minor
          categories: Style
          path_patterns:
            - .rubocop.yml
            - .rubocop_todo.yml
            - .travis.yml

  markdownlint:
    enabled: true

  rubocop:
    enabled: true

  shellcheck:
    enabled: true

exclude_patterns:
  - coverage/
  - .bundle/
