#
# For a complete list of hooks, see:
# https://github.com/causes/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/causes/overcommit#configuration
#
gemfile: Gemfile

#
# Hooks that are run after `git commit` is executed, before the commit message
# editor is displayed.
#
PreCommit:
  ClangFormat:
    description: Formatting C files with clang-format
    enabled: true
    required_executable: clang-format
    include: ext/byebug/*.[ch]
    flags: ['-style=file']

  ExecutePermissions:
    enabled: true
    exclude:
      - bin/byebug
      - script/*
