# Until https://github.com/bbatsov/rubocop/issues/1151 is closed
AllCops:
  Exclude:
    - tmp/**/*
    - pkg/**/*

TrivialAccessors:
  ExactNameMatch: true

Style/ModuleFunction:
  Enabled: false

# https://github.com/bbatsov/rubocop/issues/1466
Style/SingleLineBlockParams:
  Enabled: false

# https://github.com/bbatsov/rubocop/pull/72
Style/AsciiComments:
  Enabled: false

inherit_from: .rubocop_todo.yml
