AllCops:
  Exclude:
    - tmp/**/*

  DisplayCopNames: true
  DisplayStyleGuide: true

TrivialAccessors:
  ExactNameMatch: true

Style/ModuleFunction:
  Enabled: false

# https://github.com/bbatsov/rubocop/pull/72
Style/AsciiComments:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: false

inherit_from: .rubocop_todo.yml
