# Until https://github.com/bbatsov/rubocop/issues/1151 is closed
AllCops:
  Exclude:
    - tmp/**/*
    - pkg/**/*

TrivialAccessors:
  ExactNameMatch: true

Lint/Debugger:
  Enabled: false

inherit_from: .rubocop_todo.yml
