os:
- linux
- osx

language: ruby

install:
- ["$TRAVIS_OS_NAME" == "linux"] && sudo apt-get install indent
- bundle install --jobs=3 --retry=3

script:
- ["$TRAVIS_OS_NAME" == "osx"] && bundle exec rake compile test rubocop
- ["$TRAVIS_OS_NAME" == "linux"] && bundle exec rake

rvm:
- 2.0.0
- 2.1
- 2.2
- ruby-head

matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: 2.2

addons:
  code_climate:
    repo_token: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408
