---

os: osx
sudo: false

cache:
  directories:
    - .bundle

language: ruby

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head

env:
  global: "NOCOV=true"

  matrix:
    - "LIBEDIT=true"
    - "LIBEDIT=false"

before_install:
  - if [ "$LIBEDIT" == "true" ]; then
      brew install libedit;
    fi

install:
  - gem update --system 2.7.7
  - gem install bundler --version 1.16.4

  - if [ "$LIBEDIT" == "true" ]; then
      rvm reinstall "$TRAVIS_RUBY_VERSION" --configure --enable-libedit;
    fi

script:
  - bin/ci.sh

matrix:
  fast_finish: true

  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: change
