sudo: false

os:
  - linux
  - osx

language: ruby

before_script:
  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - gem update --system --no-document || test true
  - gem install bundler --no-document || test true
  - bundle install --jobs 3 --retry 3
  - bundle exec rake clobber compile test
  - if [ $TRAVIS_OS_NAME = linux ]; then
      bundle exec rake sign_hooks overcommit;
    fi

rvm:
  - 2.0.0
  - 2.1
  - 2.2.2
  - ruby-head

env:
  - CC=gcc
  - CC=clang

matrix:
  exclude:
    - rvm: ruby-head
      os: osx

  allow_failures:
  - rvm: ruby-head

  fast_finish: true

addons:
  code_climate:
    repo_token: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408
  apt:
    packages:
      - indent
