os:
  - linux
  - osx

language: ruby

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install indent; fi
  - bundle install --without=development --jobs=3 --retry=3

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bundle exec rake ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bundle exec rake compile test ; fi

rvm:
  - 2.0.0
  - 2.1
  - 2.2.1
  - ruby-head

env:
  - CC=gcc
  - CC=clang

matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true

addons:
  code_climate:
    repo_token: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408
