os:
- linux
- osx

language: ruby

before_script: bundle exec rake compile

rvm:
- 2.0.0
- 2.1
- 2.2
- ruby-head

matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: 2.2

addons:
  code_climate:
    repo_token: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408
