---

sudo: false

language: ruby

install:
  - gem update --system --no-document || test true
  - gem install bundler --no-document || test true
  - bundle install --jobs 3 --retry 3

before_script:
  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - bundle exec rake clobber compile test sign_hooks overcommit

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head

env:
  - CC=gcc
  - CC=clang

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.0.0

  fast_finish: true

addons:
  code_climate:
    repo_token: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408
  apt:
    sources:
      - trusty
      - debian-sid
    packages:
      - indent
      - shellcheck
