version: "{build}"

branches:
  only:
    - master

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem update --system || test true
  - gem --version
  - appveyor DownloadFile %bundler_url% -FileName bundler.gem
  - gem install --local bundler.gem --no-document
  - bundler --version
  - bundle install --without development --jobs 3 --retry 3

build_script:
  - bundle exec rake compile

test_script:
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: '200'
    - ruby_version: 200-x64
    - ruby_version: '21'
    - ruby_version: 21-x64
    - ruby_version: '22'
    - ruby_version: 22-x64

  bundler_url: https://rubygems.org/downloads/bundler-1.9.3.gem

  codeclimate_repo_token: '02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad
41cab138408'

matrix:
  fast_finish: true
