---

version: 2

steps: &steps
  steps:
    - checkout

    - run:
        name: Install coverage reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.5.1-linux-amd64 > cc-test-reporter
          chmod +x cc-test-reporter

    - restore_cache:
        keys:
          - dependencies-{{ checksum "Gemfile.lock" }}

    - run:
        name: Run CI checks
        command: bin/ci.sh

    - run:
        name: Save coverage
        command: cc-test-reporter format-coverage --output coverage/codeclimate.$CIRCLE_JOB.json

    - persist_to_workspace:
        root: ./coverage
        paths:
          - codeclimate.*.json

    - save_cache:
        key: dependencies-{{ checksum "Gemfile.lock" }}
        paths:
          - .vendor/bundle

jobs:
  2.3.7-readline-gcc:
    docker:
      - image: deividrodriguez/byebug:2.3.7-readline-gcc
    <<: *steps

  2.3.7-libedit-gcc:
    docker:
      - image: deividrodriguez/byebug:2.3.7-libedit-gcc
    <<: *steps

  2.3.7-readline-clang:
    docker:
      - image: deividrodriguez/byebug:2.3.7-readline-clang
    <<: *steps

  2.3.7-libedit-clang:
    docker:
      - image: deividrodriguez/byebug:2.3.7-libedit-clang
    <<: *steps

  2.4.4-readline-gcc:
    docker:
      - image: deividrodriguez/byebug:2.4.4-readline-gcc
    <<: *steps

  2.4.4-libedit-gcc:
    docker:
      - image: deividrodriguez/byebug:2.4.4-libedit-gcc
    <<: *steps

  2.4.4-readline-clang:
    docker:
      - image: deividrodriguez/byebug:2.4.4-readline-clang
    <<: *steps

  2.4.4-libedit-clang:
    docker:
      - image: deividrodriguez/byebug:2.4.4-libedit-clang
    <<: *steps

  2.5.1-readline-gcc:
    docker:
      - image: deividrodriguez/byebug:2.5.1-readline-gcc
    <<: *steps

  2.5.1-libedit-gcc:
    docker:
      - image: deividrodriguez/byebug:2.5.1-libedit-gcc
    <<: *steps

  2.5.1-readline-clang:
    docker:
      - image: deividrodriguez/byebug:2.5.1-readline-clang
    <<: *steps

  2.5.1-libedit-clang:
    docker:
      - image: deividrodriguez/byebug:2.5.1-libedit-clang
    <<: *steps

  upload_coverage:
    docker:
      - image: deividrodriguez/byebug:2.5.1-readline-clang
        environment:
          - CC_TEST_REPORTER_ID: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408

    steps:
      - attach_workspace:
          at: ./coverage
      - run:
          name: Upload coverage results to Code Climate
          command: |
            cc-test-reporter sum-coverage coverage/codeclimate.*.json
            cc-test-reporter upload-coverage

workflows:
  version: 2

  test:
    jobs:
      - 2.3.7-readline-gcc
      - 2.3.7-libedit-gcc
      - 2.3.7-readline-clang
      - 2.3.7-libedit-clang

      - 2.4.4-readline-gcc
      - 2.4.4-libedit-gcc
      - 2.4.4-readline-clang
      - 2.4.4-libedit-clang

      - 2.5.1-readline-gcc
      - 2.5.1-libedit-gcc
      - 2.5.1-readline-clang
      - 2.5.1-libedit-clang

      - upload_coverage:
          requires:
            - 2.3.7-readline-gcc
            - 2.3.7-libedit-gcc
            - 2.3.7-readline-clang
            - 2.3.7-libedit-clang

            - 2.4.4-readline-gcc
            - 2.4.4-libedit-gcc
            - 2.4.4-readline-clang
            - 2.4.4-libedit-clang

            - 2.5.1-readline-gcc
            - 2.5.1-libedit-gcc
            - 2.5.1-readline-clang
            - 2.5.1-libedit-clang
