---

name: windows

on: [push]

jobs:
  test:
    runs-on: windows-2019

    strategy:
      matrix:
        version: ["2.4.x", "2.5.x", "2.6.x"]

    steps:
      - uses: actions/checkout@master

      - name: Setup released rubies
        uses: MSP-Greg/actions-ruby@master
        with:
          ruby-version: ${{ matrix.version }}

      - name:
        run: |
          bin/setup_rubygems_and_bundler.sh
          git clone -q --depth=5  --no-tags --branch=byebug https://github.com/MSP-greg/rb-readline.git /tmp/rb-readline
          cd /tmp/rb-readline
          rake install

      - name: Run CI checks
        run: |
          bundle install --jobs 3 --retry 3
          ruby -rbundler/setup -e 'require "readline"; puts $LOADED_FEATURES.select{|r| r =~ /readline/}'
          bin/rake compile test
        shell: bash

    timeout-minutes: 15
