---

name: windows

on: [pull_request, push]

jobs:
  test:
    runs-on: windows-2019

    strategy:
      matrix:
        version: [2.5.8, 2.6.6, head]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: .bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}

      - name: Install dependencies
        run: bundle install

      - name: Run CI checks
        run: bundle exec rake
        continue-on-error: ${{ matrix.version == 'head' }}
