---

name: windows

on: [pull_request, push]

jobs:
  test:
    runs-on: windows-2019

    strategy:
      matrix:
        version: [2.4, 2.5, 2.6, head]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: .bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Run CI checks
        run: |
          bin/setup.sh
          bin/rake
        shell: bash
        continue-on-error: ${{ matrix.version == 'head' }}
